-- PescaGo initial schema (PostgreSQL greenfield).
-- Reproduces audited legacy structure: no FKs, no secondary indexes, no column DEFAULTs for Java values.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    username VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE carriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(255),
    name VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT carriers_pkey PRIMARY KEY (id)
);

CREATE TABLE entreprenuers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    name VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT entreprenuers_pkey PRIMARY KEY (id)
);

CREATE TABLE requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    carrier_id BIGINT,
    carrier_name VARCHAR(255),
    delivery_location VARCHAR(255),
    height DOUBLE PRECISION,
    length DOUBLE PRECISION,
    width DOUBLE PRECISION,
    entrepreneur_id BIGINT,
    entrepreneur_name VARCHAR(255),
    package_description VARCHAR(255),
    pickup_date_time TIMESTAMP WITHOUT TIME ZONE,
    pickup_location VARCHAR(255),
    price DOUBLE PRECISION,
    quantity INTEGER,
    status VARCHAR(255),
    weight_total DOUBLE PRECISION,
    CONSTRAINT requests_pkey PRIMARY KEY (id)
);

CREATE TABLE hired_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    driver VARCHAR(255),
    plate VARCHAR(255),
    vehicle_brand VARCHAR(255),
    carrier_id BIGINT,
    carrier_name VARCHAR(255),
    entrepreneur_id BIGINT,
    entrepreneur_name VARCHAR(255),
    package_description VARCHAR(255),
    payment_method VARCHAR(255),
    pickup_date_time TIMESTAMP WITHOUT TIME ZONE,
    request_id BIGINT,
    status VARCHAR(255),
    CONSTRAINT hired_services_pkey PRIMARY KEY (id)
);

CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    card_number VARCHAR(255),
    cvv VARCHAR(255),
    expiry_date VARCHAR(255),
    holder_name VARCHAR(255),
    payment_date VARCHAR(255),
    request_id BIGINT,
    CONSTRAINT receipts_pkey PRIMARY KEY (id)
);
