-- PescaGo v2 Fleet foundation — evolutive migration after Flyway baseline V1.
-- Do not modify V1__initial_schema.sql.
-- Do not apply this migration manually to pescago during local authoring; use the controlled ops window.

CREATE TABLE fleet_vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    carrier_id BIGINT NOT NULL,
    plate VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(30) NOT NULL,
    max_weight_kg NUMERIC(10, 2) NOT NULL,
    max_volume_m3 NUMERIC(10, 3),
    refrigerated BOOLEAN NOT NULL DEFAULT FALSE,
    availability_status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fleet_vehicles_pkey PRIMARY KEY (id),
    CONSTRAINT uq_fleet_vehicles_plate UNIQUE (plate),
    CONSTRAINT fk_fleet_vehicles_carrier
        FOREIGN KEY (carrier_id) REFERENCES carriers (id) ON DELETE RESTRICT
);

CREATE INDEX idx_fleet_vehicles_carrier_active
    ON fleet_vehicles (carrier_id, active);
